language: python
matrix:
  include:
  - os: linux
    sudo: false
    python: '2.7'
  - os: linux
    dist: trusty
    sudo: false
    python: '3.6'
  - os: linux
    sudo: false
    python: '3.7'
    dist: xenial
    env: BUILD_SDIST=true
    
script:
  - python -V
  - python tests/__init__.py

before_deploy: echo $TRAVIS_TAG > version.txt
deploy:
  provider: pypi
  user: guyingzhao
  on:
    tags: true
    condition: "$TRAVIS_TAG =~ [0-9]+\\.[0-9]+\\.[0-9]+ && $BUILD_SDIST = true"
  password: $PYPI_PASSWORD
